services:
  db:
    image: postgres:13
    container_name: uncreativity-ms-curso
    environment:
      POSTGRES_DB: curso_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - backend 
    volumes:
      - db-data-curso:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db-data-curso:

networks:
  backend:
    driver: bridge
