definitions:
  request.CreateCursoCarritoRequest:
    properties:
      carrito_id:
        type: integer
      curso_id:
        type: integer
    required:
    - carrito_id
    - curso_id
    type: object
  request.DeleteCursoCarritoRequest:
    properties:
      carrito_id:
        type: integer
      curso_id:
        type: integer
    required:
    - carrito_id
    - curso_id
    type: object
  response.CarritoCreateResponse:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
  response.CarritoFindAllResponse:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/response.CarritoResponse'
        type: array
      status:
        type: string
    type: object
  response.CarritoFindbyResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/response.CarritoResponse'
      status:
        type: string
    type: object
  response.CarritoResponse:
    properties:
      carrito_id:
        type: integer
      cliente_id:
        type: integer
    type: object
  response.CarritoUpdateResponse:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
  response.CursoCarritoCreateResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/request.CreateCursoCarritoRequest'
      status:
        type: string
    type: object
  response.CursoCarritoDeleteAllResponse:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
  response.CursoCarritoDeleteOneResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/request.DeleteCursoCarritoRequest'
      status:
        type: string
    type: object
  response.CursoCarritoFindAllResponse:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/response.CursoCarritoResponse'
        type: array
      status:
        type: string
    type: object
  response.CursoCarritoFindbyResponse:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/response.CursoResponse'
        type: array
      status:
        type: string
    type: object
  response.CursoCarritoResponse:
    properties:
      carrito_id:
        type: integer
      curso_id:
        type: integer
    type: object
  response.CursoResponse:
    properties:
      curso_id:
        type: integer
    type: object
  response.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  response.GetCantidadCursos:
    properties:
      code:
        type: integer
      data:
        type: integer
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /carrito:
    get:
      consumes:
      - application/json
      description: get carritos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CarritoFindAllResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Devuelve todos los carritos de la base de datos
      tags:
      - carritos
  /carrito/{id}:
    get:
      consumes:
      - application/json
      description: Busca un carrito por ID
      parameters:
      - description: CARRITO ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CarritoFindbyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Devuelve por ID un único carrito
      tags:
      - carritos
  /carrito/cursos:
    get:
      consumes:
      - application/json
      description: get cursos para cada carrito
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CursoCarritoFindAllResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Devuelve para todos los carritos, los cursos que contiene
      tags:
      - carritos
  /cliente/{cliente_id}/carrito:
    delete:
      description: Elimina un carrito a partir del ID del cliente
      parameters:
      - description: ID del cliente
        in: path
        name: cliente_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CarritoUpdateResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Elimina un carrito
      tags:
      - carritos
    post:
      description: Agrega un carrito a la base de datos
      parameters:
      - description: id cliente
        in: path
        name: cliente_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CarritoCreateResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Crea un carrito
      tags:
      - carritos
  /cliente/{cliente_id}/carrito/curso:
    get:
      description: Busca cursos por cliente id
      parameters:
      - description: CLIENTE ID
        in: path
        name: cliente_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CursoCarritoFindbyResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Devuelve los cursos que tiene un carrito por cliente ID
      tags:
      - carritos
  /cliente/{cliente_id}/carrito/curso/{curso_id}:
    delete:
      consumes:
      - application/json
      description: Para un carrito se eliminar un curso
      parameters:
      - description: Cliente ID
        in: path
        name: cliente_id
        required: true
        type: integer
      - description: Curso ID
        in: path
        name: curso_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CursoCarritoDeleteOneResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Elemina un curso de un carrito
      tags:
      - carritos
    post:
      description: Agrega un curso a un carrito mediante body
      parameters:
      - description: Cliente ID
        in: path
        name: cliente_id
        required: true
        type: integer
      - description: Curso ID
        in: path
        name: curso_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CursoCarritoCreateResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Agrega un curso a un carrito
      tags:
      - carritos
  /cliente/{cliente_id}/carrito/curso/all:
    delete:
      description: Elimina todos los cursos de un cliente
      parameters:
      - description: Cliente ID
        in: path
        name: cliente_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CursoCarritoDeleteAllResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Elimina todos los cursos a partir del id cliente
      tags:
      - cliente
    get:
      description: cantidad cursos
      parameters:
      - description: Cliente ID
        in: path
        name: cliente_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.GetCantidadCursos'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: catnid cursos
      tags:
      - cliente
swagger: "2.0"
