version: '3'
services:
  postgres:
    image: postgres:13
    restart: always
    container_name: uncreativity-ms-usuario
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    networks:
      - backend
    ports:
      - "5434:5432"
    volumes:
      - db-data-users:/var/lib/postgresql/data
volumes:
  db-data-users:

networks:
  backend:
    driver: bridge
